### ISSUE TITLE
concatfragments.sh parmas check is unsafe and may work not as intended

### ISSUE THREAD

**Issue by acca301** [puppetlabs/puppetlabs-concat#120]
For example
-w parameter value is expected to be a single word in line 108 of concatfragments.sh:
        if [ x${WARNMSG} = "x" ]; then

obviously, it should be
        if [ "x${WARNMSG}" = "x" ]; then

the same applies for the rest of  [ x${XXXX} = "x" ] checks through the file.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
