### ISSUE TITLE
concat isn't playing nicely with SELinux

### ISSUE THREAD

**Issue by jpjp** [puppetlabs/puppetlabs-concat#122]
It seems that concat builds a config from fragments in a directory with a given SELinux type (puppet_var_lib_t) and then _moves_ the resulting file to the destination.

SELinux will maintain the label for a file on a move, leading to the resulting config file being unreadable to the process that should use it (e.g. postgres).

A copy would workaround this issue.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
