### ISSUE TITLE
/var might be mounted with noexec options

### ISSUE THREAD

**Issue by ghost** [puppetlabs/puppetlabs-concat#130]
Since /var might be mounted with the noexec option there should be a way to set the variable $script_path to a different value. I'm not sure if the following diff is the best way to do it, though:

diff --git a/manifests/setup.pp b/manifests/setup.pp
index 8d36478..0707467 100644
--- a/manifests/setup.pp
+++ b/manifests/setup.pp
@@ -25,7 +25,11 @@ class concat::setup {
     default   => 'concatfragments.sh'
   }
-  $script_path = "${concatdir}/bin/${script_name}"
-  if $::concat_script_path {
-    $script_path = $::concat_script_path
-  } else {
-    $script_path = "${concatdir}/bin/${script_name}"
-  }
  
  $script_command   = $::kernel ? {
   'windows' => "ruby.exe ${script_path}",

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
