### ISSUE TITLE
feature request: new parameter: order => close

### ISSUE THREAD

**Issue by poikilotherm** [puppetlabs/puppetlabs-concat#137]
Sometimes one would like to have ordered concats, defining a preamble and a close text within the concatenated file.

It is hard to ensure an appropriate numbering/... for the close if you concat from multiple places/modules. A parameter "order => close" as a reserved value for the order parameter of concat::fragment could be a solution to this situation, if it ensures that this very fragment gets included last to the target.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
