### ISSUE TITLE
order => numeric option doesn't seem to work

### ISSUE THREAD

**Issue by ashak** [puppetlabs/puppetlabs-concat#4]
As described on the puppet irc channel, order => numeric doesn't seem to work.

This seems to be related to find and the fact that all files found start with fragments/ before the number.

Simple patch (suggested by richardc) seems to be:
    diff --git a/files/concatfragments.sh b/files/concatfragments.sh
    index 52fd684..884de5d 100644
    --- a/files/concatfragments.sh
    +++ b/files/concatfragments.sh
    @@ -44,7 +44,7 @@ WORKDIR=""
     TEST=""
     FORCE=""
     WARN=""
    -SORT1="-z"
    +SORT1="-z -t / -k 2"
     SORT2=""
     FINDARG="-print0"
     XARGSARG="-0"`

This works for me at least on an Ubuntu box.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
