### ISSUE TITLE
Fragments containing star "*" in filename generated duplicatd lines

### ISSUE THREAD

**Issue by brunoleon** [puppetlabs/puppetlabs-concat#69]
Recently I discovered that if a fragments contains a star in its filename, there will be multiple concatenation if multiple fragments filename start with the same pattern.

This comes from the shell expending filename when doing the "cat" operation.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
