### ISSUE TITLE
v8 fails with create_empty_file

### ISSUE THREAD

**Issue by elfranne** [puppetlabs/puppetlabs-concat#772]
## Describe the Bug
`create_empty_file` introduced in #766 (v7.4) is broken after #768 (v8):

```log
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'create_empty_file' (file: /etc/puppetlabs/code/environments/CONCAT/modules/concat/manifests/init.pp, line: 126) on Concat_file[/etc/samba/smb.conf] (file: /etc/puppetlabs/code/environments/CONCAT/modules/concat/manifests/init.pp, line: 126) on node [redacted]
```

This occurred with this [module](https://forge.puppet.com/modules/millerjl1701/samba), `concat` is called [here](https://github.com/millerjl1701/millerjl1701-samba/blob/master/manifests/config.pp) 

## Environment
 - module version 7.4 and 8
 - puppet 7.24, Ubuntu 20.04

**Comment by LukasAud** [comment]
Hi @elfranne, we are investigating this. However, this is an odd failure, as our CI doesn't seem to be picking up any failure with that feature after the Puppet 8 upgrade. Can you confirm me if you have encountered this issue outside of the usage of the Samba module? 

If this issue has only been encountered within the mentioned module, one possible point of failure could be here: 
https://github.com/millerjl1701/millerjl1701-samba/blob/master/metadata.json#L13
It seems like the module might be expecting concat versions < 7.0.0, while receiving concat v8.0.0

**Comment by elfranne** [comment]
Yep that was it, fixed metadata in the samba modules solve the issue.
https://github.com/elfranne/millerjl1701-samba
