### ISSUE TITLE
 Server Error: no parameter named 'create_empty_file'

### ISSUE THREAD

**Issue by buzzdeee** [puppetlabs/puppetlabs-concat#782]
## Describe the Bug

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'create_empty_file' (file: /etc/puppetlabs/code/environments/production/modules/concat/manifests/init.pp, line: 126) on Concat_file[/usr/local/bin/some_file.sh] (file: /etc/puppetlabs/code/environments/production/modules/concat/manifests/init.pp, line: 126) on node XXXXX`

## Expected Behavior
should just work

## Environment
 - Version Git rev: e3fe096e08d2477b58bdfb3372d478a33a447280
 - Platform OpenBSD 7.2
 - Puppet puppet-7.23.0
 - Puppetserver puppetserver-7.9.5
 - Ruby: ruby-3.1.3

## Additional Context
removing the 'create_empty_file' parameter in init.pp in concat_file following line 126 fixes the trouble for me.

**Comment by ekohl** [comment]
On the puppetserver you may need to run `puppet generate types` (https://www.puppet.com/docs/puppet/7/man/generate.html#actions) because puppetserver sometimes has problems isolating environments with custom types.

**Comment by buzzdeee** [comment]
never ran puppet generate types before

```
puppet generate types --verbose --debug --trace
Debug: Runtime environment: puppet_version=7.23.0, ruby_version=3.1.3, run_mode=user, default_encoding=US-ASCII
Debug: Searching environment 'production' for custom types.
Debug: Evicting cache entry for environment :production
Debug: Deleted text domain :production: false
Error: no implicit conversion of nil into String
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/face/generate.rb:54:in `join'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/face/generate.rb:54:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/interface/action.rb+eval[wrapper]:261:in `types'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/application/face_base.rb:254:in `main'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/application.rb:437:in `run_command'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/application.rb:421:in `block in run'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/util.rb:756:in `exit_on_fail'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/application.rb:421:in `run'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/util/command_line.rb:143:in `run'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/lib/puppet/util/command_line.rb:77:in `execute'
/usr/local/lib/ruby/gems/3.1/gems/puppet-7.23.0/bin/puppet:5:in `<top (required)>'
/usr/local/bin/puppet:25:in `load'
/usr/local/bin/puppet:25:in `<main>'
Error: Try 'puppet help generate types' for usage
```

seems there's something else I've to work out first ;)

**Comment by buzzdeee** [comment]
didn't figured out the problem to 'puppet generate type' error, but restarting puppetserver did the trick as well for the time being.

**Comment by jjarokergc** [comment]
I just ran into this error message on Puppet version 8 after updating the concat version. The solution is to restart puppet server
```
service puppetserver restart
```
