### ISSUE TITLE
v9.0.1 breaks compatibility with pre-Puppet 7.17

### ISSUE THREAD

**Issue by nmburgan** [puppetlabs/puppetlabs-concat#803]
## Describe the Bug
[This](https://github.com/puppetlabs/puppetlabs-concat/commit/c7ffb954d2bdf5d56e3ded39c7d93b2d74960a77) breaks compatibility with pre-7.17 agents, as this was not implemented until then.  For example, when the postgresql module uses it with a Puppet 6 agent:
```
Error: /Stage[main]/Postgresql::Server::Config/Postgresql::Server::Instance::Config[main]/Concat[/var/lib/pgsql/14/data/pg_hba.conf]/Concat_file[/var/lib/pgsql/14/data/pg_hba.conf]: Failed to generate additional resources using 'eval_generate': uninitialized constant Puppet::Pops::Evaluator::DeferredValue
Did you mean?  Puppet::Pops::Evaluator::DeferredResolver
```

May want to do something like this instead:
`fragment_content = r[:content].respond_to?(:resolve) ? r[:content].resolve : r[:content]`

I know the metadata says this version requires Puppet 7 at least, but I think this might be the only bit that breaks Puppet 6.

## Expected Behavior
Concat works correctly with pre-Puppet 7.17 agents.

**Comment by ekohl** [comment]
The metadata says the lower bound is Puppet 7.0.0. I don't think we'll bring back Puppet 6 support but if we claim 7.0.0, that should work. Or we should raise it.

**Comment by Ramesh7** [comment]
Thanks @nmburgan for reporting this with detailed summary as well as proposing the solution too.
Have raised internal ticket and will priorities the same.
