### ISSUE TITLE
concat::fragment does not append a string to a file

### ISSUE THREAD

**Issue by apt4user** [puppetlabs/puppetlabs-concat#811]
## Describe the Bug
I've installed the module puppetlabs-concat version 8.0.1 but when I declare

```
concat { '/path/to/file':
  ensure => present,
}

concat::fragment { 'tmpfile':
   target  => '/path/to/file',
   content => 'test contents',
   order   => 'ZZ'
}
```
and after that, when i perform a puppet run, the file gets overridden
## Expected Behavior
I wanted to append a string to an existing file

## Steps to Reproduce
Apply the above mentioned code

## Environment
 - Version [8.0.1]
 - Platform [Ubuntu 22.04]
- Puppet version: 8.6.0

**Comment by kenyon** [comment]
This module isn't used for appending to existing files like that.
